name: main-workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: run lint
        run: make lint

      - name: test
        run: make test

      # - name: test and publish code coverage
      #   uses: paambaati/codeclimate-action@v5.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #   with:
      #     coverageCommand: make coverage
      #     debug: true
      #     coverageLocations: ${{github.workspace}}/coverage/cobertura-coverage.xml:cobertura
